In [1]:
import numpy as np
def sigmoid (x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative (x):
    return x * (1 - x)

training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

training_outputs1 = np.array([[0,1,1,0]]) 

training_outputs = training_outputs1.T

np.random.seed(1)

synaptic_weights =  2 * np.random.random((3,1)) - 1

print ('Random starting synaptic weights:')
print (synaptic_weights)

for iteration in range (200000):
    
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs) #weadjust the weightds
    #according to the error and the sigmoid deriv. @ the outputs, since
    #large sig.der. indicate low confidence, and the weights are penalized 
    #accordingly and vice versa
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Outputs after training:')
print(outputs)


Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Outputs after training:
[[0.00213009]
 [0.99826132]
 [0.99858161]
 [0.00173782]]


In [2]:
print(training_inputs)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
